#OPERADORES ARITMETICOS +,-,*,//,/,%,**
#OPERADORES RELCIONALES O DE COMPARACIÓN >,<,>=.<=,==,!=
#OPERADORES DE ASIGNACIÓN 
#=, +=, -=, /= ...
#DEBILMENTE TIPADO (PHYTON)
#x=100
#x=x+100
#x*=100
#OPERADORES LÓGICOS
#AND, OR, NOT
x=10
y=20
print(y>x and y>100)
